clc; clear; close all;
RAND_MAX = 32767;
camera_ray = [0; 0; 1];
path = 'C:\Developer\hmodel-cuda-build\data\';

[centers, radii, blocks, theta, mean_centers] = read_cpp_model(path);

%% Read semantics
input_path = '_my_hand/final/';
semantics_path = '_my_hand/semantics/';
load([semantics_path, 'fitting/names_map.mat']);
%blocks = blocks(1:28);
palm_blocks = {
    [names_map('thumb_base'), names_map('thumb_bottom'), names_map('thumb_fold')], ...
    [names_map('palm_ring'), names_map('palm_pinky'), names_map('palm_right')], ...
    [names_map('palm_back'), names_map('palm_ring'), names_map('palm_right')], ...
    [names_map('palm_back'), names_map('palm_ring'), names_map('palm_middle')], ...
    [names_map('palm_back'), names_map('palm_left'), names_map('palm_middle')], ...
    [names_map('palm_left'), names_map('palm_middle'), names_map('palm_index')], ...
    [names_map('pinky_membrane'), names_map('palm_pinky'), names_map('ring_membrane')], ...
    [names_map('palm_ring'), names_map('palm_pinky'), names_map('ring_membrane')], ...
    [names_map('palm_ring'), names_map('middle_membrane'), names_map('ring_membrane')], ...
    [names_map('palm_ring'), names_map('palm_middle'), names_map('middle_membrane')], ...
    [names_map('palm_middle'), names_map('palm_index'), names_map('middle_membrane')], ...
    [names_map('palm_index'), names_map('index_membrane'), names_map('middle_membrane')], ...
    [names_map('thumb_base'), names_map('thumb_fold'), names_map('palm_thumb')], ...
    [names_map('wrist_bottom_left'), names_map('wrist_top_left'), names_map('wrist_top_right')], ...
    [names_map('wrist_bottom_right'), names_map('wrist_bottom_left'), names_map('wrist_top_right')]
    };

fingers_blocks{1} = {[names_map('pinky_middle'), names_map('pinky_top')], ...
    [names_map('pinky_bottom'), names_map('pinky_middle')], ...
    [names_map('pinky_base'), names_map('pinky_bottom')]};
fingers_blocks{2} = {[names_map('ring_top'), names_map('ring_middle')], ...
    [names_map('ring_bottom'), names_map('ring_middle')], ...
    [names_map('ring_bottom'), names_map('ring_base')]};
fingers_blocks{3} = {[names_map('middle_top'), names_map('middle_middle')], ...
    [names_map('middle_bottom'), names_map('middle_middle')], ...
    [names_map('middle_bottom'), names_map('middle_base')]};
fingers_blocks{4} = {[names_map('index_middle'), names_map('index_top')], ...
    [names_map('index_bottom'), names_map('index_middle')], ...
    [names_map('index_base'), names_map('index_bottom')]};
fingers_blocks{5} = {[names_map('thumb_top'), names_map('thumb_additional')], ...
    [names_map('thumb_top'), names_map('thumb_middle')], ...
    [names_map('thumb_bottom'), names_map('thumb_middle')]};

display_result(centers, [], [], blocks, radii, false, 1, 'big');
view([-180, -90]);

%% Find outline
[final_outline] = find_model_outline(centers, radii, blocks, palm_blocks, fingers_blocks, camera_ray, names_map, true, true);


